### ISSUE TITLE
Removed from WordPress.org?

### ISSUE THREAD

**Issue by jonahcoyote** [dylanblokhuis/instantcss-wp#30]
Hi there,

This is one of my favorite WP plugins and indispensable to my workflow so thank you for making it! Unfortunately I saw that WP just removed it from their repository. Any idea why?

Regards,
Jonah

**Comment by dylanblokhuis** [comment]
Hi Jonah,

Unfortunately there was a security issue, hence it got removed from the WordPress directory. I pushed a fix for this and it should be up again soon.

**Comment by jonahcoyote** [comment]
Awesome, thank you sir!
